appName: &APP psh
logName: *APP

debug: true

port: 8000
address: 127.0.0.1
use_pool: true
max_connections: 10000

time_format: "MM/DD/YYYY hh:mm a"

files:
  pid: psh.pid
  log: psh.log
  stderr: psh_error.log
  stdout: psh_out.log

dirs:
  pid: pid/
  log: logs/
  base: /srv/http/
  nginx: /nginx_config/
  templates: views/raw_templates/

databases:
  rethink:
    db: psh
  redis:
    db: 0
    URL: localhost

docker:
  url: http://127.0.0.1
  port: 3945
  version: 1.7
  timeout: 600

builder:
  log_name: psh_builder

  files:
    pid: psh_builder.pid
    log: psh_builder.log
    stderr: psh_builder_error.log
    stdout: psh_builder_out.log

  dirs:
    pid: pid/
    log: logs/

spinner:
  log_name: psh_spinner

  files:
    pid: psh_spinner.pid
    log: psh_spinner.log
    stderr: psh_spinner_error.log
    stdout: psh_spinner_out.log

  dirs:
    pid: pid/
    log: logs/
