+++
nav: new
+++
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <form method="POST" enctype="multipart/form-data">
      <fieldset>
        <div class="form-group {{ 'has-error' if error }}">
          <input type="file" class="form-control" id="file" name="file">
          {% if error %}
            <span class="help-block">
              There seems to be something missing in this file: {{error}}
            </span>
          {% endif %}
        </div>

        <div class="form-group">
          <input type="text" class="form-control" id="name" name="name" placeholder="Dockerfile Name..." value="{{name}}" required>
        </div>
        <!--
        <div class="checkbox">
          <label>
            <input type="checkbox" name="public" value="true" {{ 'checked' if public }}> Make this publically viewable?
          </label>
        </div>-->
        <hr>
        <button class="btn btn-theme btn-block" type="submit">Upload</button>
      </fieldset>
    </form>
  </div>
</div>
